/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as OmRouteImport } from './routes/om'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatistikLabbRouteImport } from './routes/statistik.labb'
import { Route as LofteIdRouteImport } from './routes/lofte.$id'

const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikLabbRoute = StatistikLabbRouteImport.update({
  id: '/labb',
  path: '/labb',
  getParentRoute: () => StatistikRoute,
} as any)
const LofteIdRoute = LofteIdRouteImport.update({
  id: '/lofte/$id',
  path: '/lofte/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRouteWithChildren
  '/lofte/$id': typeof LofteIdRoute
  '/statistik/labb': typeof StatistikLabbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRouteWithChildren
  '/lofte/$id': typeof LofteIdRoute
  '/statistik/labb': typeof StatistikLabbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRouteWithChildren
  '/lofte/$id': typeof LofteIdRoute
  '/statistik/labb': typeof StatistikLabbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/om'
    | '/statistik'
    | '/lofte/$id'
    | '/statistik/labb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/om'
    | '/statistik'
    | '/lofte/$id'
    | '/statistik/labb'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/om'
    | '/statistik'
    | '/lofte/$id'
    | '/statistik/labb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  OmRoute: typeof OmRoute
  StatistikRoute: typeof StatistikRouteWithChildren
  LofteIdRoute: typeof LofteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik/labb': {
      id: '/statistik/labb'
      path: '/labb'
      fullPath: '/statistik/labb'
      preLoaderRoute: typeof StatistikLabbRouteImport
      parentRoute: typeof StatistikRoute
    }
    '/lofte/$id': {
      id: '/lofte/$id'
      path: '/lofte/$id'
      fullPath: '/lofte/$id'
      preLoaderRoute: typeof LofteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StatistikRouteChildren {
  StatistikLabbRoute: typeof StatistikLabbRoute
}

const StatistikRouteChildren: StatistikRouteChildren = {
  StatistikLabbRoute: StatistikLabbRoute,
}

const StatistikRouteWithChildren = StatistikRoute._addFileChildren(
  StatistikRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  OmRoute: OmRoute,
  StatistikRoute: StatistikRouteWithChildren,
  LofteIdRoute: LofteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
